### PR TITLE
add engine.draw/engine.onDraw to support a better game loop.

### PR DESCRIPTION
**Pull request by martikaljuve**
This PR adds `engine.onDraw` in addition to `engine.onUpdate` for use in systems. This makes it easier to separate physics and render loops. 

Example (using [MainLoop](http://www.npmjs.com/packages/mainloop.js)):

```js
function SomeSystem($engine) {
    $engine.onUpdate(function(delta) {
        // Runs at a fixed timestep, e.g. 20hz or 60hz or 120hz.
    });

    $engine.onDraw(function(interpolationPercentage) {
        // Runs every requestAnimationFrame, e.g. up to 60fps.
    });
}

const engine = new Scent.Engine();
engine.addSystem(SomeSystem);
engine.start();

MainLoop.setUpdate(engine.update)
    .setDraw(engine.draw)
    .start();
```

References:
http://www.isaacsukin.com/news/2015/01/detailed-explanation-javascript-game-loops-and-timing
http://gameprogrammingpatterns.com/game-loop.html

### CODE REVIEW

**Comment by danielkcz** [comment]
I don't see any real benefit of adding this to the engine. You can use NoMe (or any other proven lib for callback list) to handle this outside Scent completely. However as I already announced, I am not really maintaining or using Scene, so if you feel like it's useful, you can merge it :)

**Comment by martikaljuve** [comment]
Thanks for the feedback! I hope you can continue to chime in with your opinions from time to time. :)

Here's a nice image from [gameprogrammingpatterns.com](http://gameprogrammingpatterns.com/game-loop.html) to explain the different loops:
image

I guess the onDraw callback could also be provided like this:
```js
const draw = NoMe();

const engine = new Scent.Engine(function(engine, provide) {
	provide('$onDraw', draw.notify);
})

function RenderSystem($engine, $onDraw) {
	$onDraw(function(interpolationPercentage) {

	});
}

engine.addSystem(RenderSystem);
engine.start();

MainLoop.setUpdate(engine.update)
	.setDraw(draw)
	.start();
```

Decoupling simulation and rendering loops is pretty common in games, so $engine seems like a good place to have this separation. I usually have most systems (collision, velocity etc.) simulate the game using the `onUpdate` loop and a single RenderSystem using the `onDraw` loop.

**Comment by danielkcz** [comment]
I understand why is separating render loop good thing, no problem there. It's just that Scent is not really a rendering engine. It just handles entities and components, rest is up to you. That's why I feel it does not belong there.

In our game attempt back in the days we had a huge app object that was passed into systems and among other things, it also had event emitter for render loop. It was working pretty well I think. There is nothing wrong with the approach in your latest comment for sure. It's just not very scalable I guess.

**Comment by martikaljuve** [comment]
Hmm, I think I agree with you. `update` has a purpose in the engine because it processes actions and nodes, but draw can live outside of the base library. Since I have a separate "game engine" with common systems and components, I can just extend `Scent.Engine` there, e.g. something like this.

```ts
import * as MainLoop from 'mainloop.js';
import * as NoMe from 'nome';
import * as Scent from 'scent';

export default class Engine extends Scent.Engine {
	draw = NoMe();

	constructor(provides?: { [key: string]: any }) {
		super(function(engine, provide) {
			const scentStart = engine.start;

			Object.assign(engine, {
				start(this: Engine) {
					scentStart.call(engine);

					MainLoop.setDraw(this.draw)
						.setUpdate(this.update)
						.start();

					return this;
				}
			});

			if (provides) {
				Object.keys(provides).forEach(function(name) {
					provide(name, provides[name]);
				});
			}
		});
	}

	onDraw(fn: (interpolationPercentage: number) => void) {
		this.draw.notify(fn);
	}
}
```

**Pull request closed without merging**
