### PR TITLE
Build with Webpack and Babel

### LINKED ISSUE #19: Browser build with dependencies
Current prebuilt file in a lib folder is not that useful as it doesn't include any dependencies. Ideally we should have a separate bundle with Scent along with bundle of dependencies that can be included if they are not supplied from anywhere else.

Consider using Webpack instead of Browserify as it's much easier to configure.

### PR DESCRIPTION
**Pull request by danielkcz**
See details of changes in separate commit messages. In general there shouldn't be any breaking change except that old bundles in _lib_ folder has been completely removed and new one is in _dist_ folder together with dependencies. Since it's UMD bundle, these will not interfere with anything globally used.

Fixes #19

### CODE REVIEW

**Comment by danielkcz** [comment]
Cool, tests are passing :)

@martikaljuve I suppose that this change should not influence you in any way, but I would be grateful if you can test it before I merge it. Since the _lib_ folder is no longer part of repo (it will be only in NPM), you would have to clone the branch, and run `npm install && npm run compile`. Then you should be able to use Browserify to create your bundle as before.

**Comment by martikaljuve** [comment]
Works fine on my pc! :+1:

**Comment by danielkcz** [comment]
Thanks you very much for checking that. I want to do some additional small changes before merging it.

**Comment by danielkcz** [comment]
This got merged some time ago already using cherry-pick.

**Pull request closed without merging**
